language: go

os:
  - linux
  - osx

go:
- "1.10"

git:
  depth: 3

go_import_path: github.com/kubernetes-sigs/controller-runtime

before_install:
- go get -u github.com/golang/dep/cmd/dep

# Install must be set to prevent default `go get` to run.
# The dependencies have already been vendored by `dep` so
# we don't need to fetch them.
install:
  - go get -u golang.org/x/lint/golint

script:
- go vet ./pkg/...
- golint -set_exit_status ./pkg/...
- TRACE=1 ./install_test.sh
- go test github.com/kubernetes-sigs/controller-runtime/pkg/...
- go install github.com/kubernetes-sigs/controller-runtime/example


# TBD. Suppressing for now.
notifications:
  email: false
