#  Copyright 2018 The Kubernetes Authors.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Packages required by users
required = ["sigs.k8s.io/testing_frameworks/integration",
            "k8s.io/client-go/plugin/pkg/client/auth",
            "github.com/spf13/pflag",
            "github.com/emicklei/go-restful",
            "github.com/go-openapi/spec",
            "k8s.io/kube-openapi/pkg/common",
            "k8s.io/apiextensions-apiserver",
            ]

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "v1.5.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "v1.4.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.8.0"

[[constraint]]
  name = "sigs.k8s.io/testing_frameworks"
  revision = "f53464b8b84b4507805a0b033a8377b225163fea"

[[constraint]]
  name = "github.com/go-logr/logr"
  revision = "9fb12b3b21c5415d16ac18dc5cd42c1cfdd40c4e"

[[constraint]]
  name = "github.com/golang/glog"
  revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"

[prune]
  go-tests = true
  unused-packages = true
